apiVersion: v1                                         # API version for defining a Kubernetes Service
kind: Service                                          # This manifest defines a Service resource
metadata:
  name: {{ include "usermanagement.fullname" . }}               # The name of the Service, typically includes release name
  namespace: {{ .Values.namespace }}                   # Namespace where the Service will be created (from values.yaml)
  labels:                                              # Labels to identify and organize the Service
    app: {{ include "usermanagement.name" . }}                  # Label for the app name
    chart: {{ include "usermanagement.chart" . }}               # Helm chart label
    release: {{ .Release.Name }}                       # Helm release name
    heritage: {{ .Release.Service }}                   # Helm service label
    environment: {{ .Values.env | quote }}             # Custom label to identify the environment (e.g., dev)

spec:
  selector:                                            # Selector to match Pods the Service should route to
    app: {{ include "usermanagement.name" . }}                  # Must match the label on the pods
    release: {{ .Release.Name }}                       # Must match the label on the pods

  ports:
    - protocol: TCP                                    # Network protocol (TCP in this case)
      port: {{ .Values.service.port }}                 # Port exposed by the Service
      targetPort: {{ .Values.service.targetPort }}           # Port on the container the traffic should be forwarded to

  type: {{ .Values.service.type | default "ClusterIP" }} # Type of Service (e.g., ClusterIP, NodePort, LoadBalancer); defaults to ClusterIP
