# values-dev.yaml
replicaCount: 1


namespace: prod

image:
  repository: mutuwa12/appointment                 # Docker image repository (in this case, the official Nginx image)
  tag: v1                       # Image tag/version to use (using 'latest' for dev environment)
  pullPolicy: IfNotPresent          # Policy for pulling images (Only pulls if not already present on node)


service:
  name: appointment-prod
  type: LoadBalancer
  targetPort: 8000
  port: 80

env: prod

resources:
  limits:
    cpu: "500m"                     # Maximum amount of CPU the container can use (500 millicores = 0.5 cores)
    memory: "256Mi"                 # Maximum memory the container can use (256 MiB)

  requests:
    cpu: "250m"                     # Minimum amount of CPU requested (used for scheduling)
    memory: "128Mi"                 # Minimum memory requested (used for scheduling)



ingress:
  enabled: true
  host: appointment-prod.com
certManager:
  issuerName: selfsigned
