# values-dev.yaml
replicaCount: 2


namespace: prod

image:
  repository: mutuwa12/frontendapp                 # Docker image repository (in this case, the official Nginx image)
  tag: v1                       # Image tag/version to use (using 'latest' for dev environment)
  pullPolicy: IfNotPresent          # Policy for pulling images (Only pulls if not already present on node)

service:
  name: frontendapp-prod
  type: LoadBalancer
  targetPort: 80
  port: 80

env: prod

resources:
  limits:
    cpu: "200m"        #
    memory: "128Mi"     # 

  requests:
    cpu: "100m"         # 
    memory: "64Mi"     # 


ingress:
  enabled: true
  host: noble-mutuwa.com
certManager:
  issuerName: selfsigned
